### ISSUE TITLE
Ballast Community Chat

### ISSUE THREAD

**Issue by seljabali** [copper-leaf/ballast#20]
Hello,

I think it'd be beneficial to create a Slack channel in the Kotlin Slack Workspace for this project. There's much to talk about in making this project bigger. 

Best,
-Sami

P.S. I'm looking for a solid KMM MVI library after finding Orbit MVI not well supported when it comes to KMM/iOS, hence want to help in that department in any way possible.

**Comment by cjbrooks12** [comment]
Yeah, that's a good idea. I'll see if I can get a channel created for Ballast
