### ISSUE TITLE
Docs website typo

### ISSUE THREAD

**Issue by charlee-dev** [copper-leaf/ballast#39]
[here](https://copper-leaf.github.io/ballast/wiki/modules/ballast-navigation/)

Missing p in `applicationScoe` -> `applicationScope`

![CleanShot 2023-01-16 at 18 32 51](https://user-images.githubusercontent.com/20965327/212745930-9bcec9ff-984e-4d16-93e5-65fccc44a898.png)

**Comment by cjbrooks12** [comment]
Nice catch! The docs site is now fixed
