### ISSUE TITLE
Compose Multiplatform iOS (Alfa) support?

### ISSUE THREAD

**Issue by jQrgen** [copper-leaf/ballast#49]
Hello

Compose multiplatform for iOS has recently been released (Alfa): https://blog.jetbrains.com/kotlin/2023/05/compose-multiplatform-for-ios-is-in-alpha/

Does Ballast support Compose multiplatform iOS (Alfa) in the current version (3.0.2)?

**Comment by cjbrooks12** [comment]
Ballast doesn't directly depend on Compose for any of its artifacts, so I would expect the current version to work fine. The basic setup is the same as for [Desktop](https://copper-leaf.github.io/ballast/wiki/platforms/compose-desktop/).
