### ISSUE TITLE
Cannot resolve debugger dependency

### ISSUE THREAD

**Issue by ubuntudroid** [copper-leaf/ballast#59]
While setting up ballast I'm not able to properly define the debugger dependency. I always get the following error while syncing:

```
Could not find io.github.copper-leaf:ballast-debugger:4.0.0
```

I did a quick maven artifact search and the artifact indeed isn't available. There are some ballast related debug artifacts (ending with `android-debug`, but I'm not sure those are the same.

**Comment by ubuntudroid** [comment]
Alright, looks like the docs need some updating - the correct dependency is `io.github.copper-leaf:ballast-debugger-client:4.0.0`. 🤓

**Comment by ubuntudroid** [comment]
Reopening as @cjbrooks12 likely wants to update the docs before closing.

**Comment by cjbrooks12** [comment]
The docs are now updated 

https://copper-leaf.github.io/ballast/wiki/modules/ballast-debugger/#installation
