### ISSUE TITLE
Could not find uri-kmp-iosx64

### ISSUE THREAD

**Issue by charlee-dev** [copper-leaf/ballast#70]
Hi. In one of my KMP Android and iOS projects, I try to bump ballast (core and navigation) from 4.0.0 to 4.2.1 bump, but I get an error:

```kotlin
> Could not resolve all files for configuration ':apps:product:product-ui:iosX64CompilationDependenciesMetadata'.
   > Could not find uri-kmp-iosx64-0.0.18.klib (com.eygraber:uri-kmp-iosx64:0.0.18).
     Searched in the following locations:
         https://plugins.gradle.org/m2/com/eygraber/uri-kmp-iosx64/0.0.18/uri-kmp-iosx64-0.0.18.klib
         https://plugins.gradle.org/m2/com/eygraber/uri-kmp-iosx64/0.0.18/uri-kmp-iosx64-0.0.18.jar
```

It seems like an issue with `uri-kmp?

**Comment by cjbrooks12** [comment]
Hmm, that seems strange that Ballast compiled if the new URI lib is missing one of the targets. Let me take a look at it today

**Comment by cjbrooks12** [comment]
Just coming back to this, did you ever find a resolution? 

From the posted error, I think there might be an issue with your project repositories. The uri-kmp library does have an iosx64 target, it's in MavenCentral at this URL, for example: https://repo1.maven.org/maven2/com/eygraber/uri-kmp-iosx64/0.0.18/. Your setup seems to only be searching for dependencies in https://plugins.gradle.org/m2, which only hosts Gradle plugins.

**Comment by charlee-dev** [comment]
i think the issue was that i had 

```kotlin
repositories {
    gradlePluginPortal()
    mavenCentral()
}
```

and flipping those to
```kotlin
repositories {
    mavenCentral()
    gradlePluginPortal()
}
```

fixed it, which is a mystery to me as I would expect it to try maven if it did;t find it in gradle plugins..
